### ISSUE TITLE
Admin form field for filtering an events list by category

### ISSUE THREAD

**Issue by floriandammeyer** [pikim/grav-plugin-events#28]
You can filter an events list (= page type "events") by using the the category taxanomy in the front matter like so:

```
content:
    items:
        '@taxonomy':
            type: event
            category: my-event-category
```

As far as I understood, the `content.items.@taxanomy.type` of the front matter corresponds to the form field "Taxonomy Type" which is shown in the "Events" tab of an "events"-page in the admin. Apparently, there is no such form field for filtering by category, so you have to edit the front matter manually if you want to filter by category. 

Adding a form field to filter by category would be very helpful for editors of our site who are not proficient in programming. Ideally this form field would suggest existing categories just like the form field in the "Options" tab does.
